spring:
  thymeleaf:
     cache: false
  jackson:
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://localhost:40002/ddbs
      database: ddbs

  cache:
    type: redis
  redis:
    host: localhost


