version: "3.9"
services:
  shardsvr1:
    container_name: shardsvr1
    image: mongo:4.4.14
    networks:
      mongodb_mongonet:
        ipv4_address: 172.20.0.6
    ports:
      - 40021:27018
    volumes:
      - shardsvr1:/data/db
    command: mongod --shardsvr --replSet shardsvr_rs1 --dbpath /data/db --bind_ip_all
    restart: always
  shardsvr2:
    container_name: shardsvr2
    image: mongo:4.4.14
    networks:
      mongonet:
        ipv4_address: 172.20.0.7
    ports:
      - 40022:27018
    volumes:
      - shardsvr2:/data/db
    command: mongod --shardsvr --replSet shardsvr_rs1 --dbpath /data/db --bind_ip_all
    restart: always
  shardsvr3:
    container_name: shardsvr3
    image: mongo:4.4.14
    networks:
      mongonet:
        ipv4_address: 172.20.0.8
    ports:
      - 40031:27018
    volumes:
      - shardsvr3:/data/db
    command: mongod --shardsvr --replSet shardsvr_rs2 --dbpath /data/db --bind_ip_all
    restart: always
  shardsvr4:
    container_name: shardsvr4
    image: mongo:4.4.14
    networks:
      mongonet:
        ipv4_address: 172.20.0.9
    ports:
      - 40032:27018
    image: mongo:4.4.14
    volumes:
      - shardsvr4:/data/db
    command: mongod --shardsvr --replSet shardsvr_rs2 --dbpath /data/db --bind_ip_all
    restart: always

volumes:
  shardsvr1: {}
  shardsvr2: {}
  shardsvr3: {}
  shardsvr4: {}

networks:
  default:
    name: mongonet
    external: true